CC = gcc
AR = ar
JAVAC = javac
JAVAH = javah
STD = -std=c99 -Wall -pedantic
OPTIMIZATION ?= -O3
OPT = $(OPTIMIZATION)
DEBUG = -g -ggdb
WARN = -Wall

JAVA_HOME := $(shell readlink -f /usr/bin/javac | sed 's:/bin/javac::')

FINAL_CFLAGS = $(STD) $(WARN) $(OPT) $(DEBUG) $(CFLAGS)
FINAL_LDFLAGS = $(LDFLAGS) $(DEBUG)
FINAL_LIBS =

FINAL_CC = $(QUIET_CC)$(CC) $(FINAL_CFLAGS)
FINAL_LD = $(QUIET_LINK)$(CC) $(FINAL_LDFLAGS)
FINAL_AR = $(QUIET_AR)$(AR)
FINAL_JAVAC = $(QUIET_JAVAC)$(JAVAC)
FINAL_JAVAH = $(QUIET_JAVAH)$(JAVAH)

CCCOLOR="\033[34m"
LINKCOLOR="\033[34;1m"
SRCCOLOR="\033[33m"
BINCOLOR="\033[37;1m"
MAKECOLOR="\033[32;1m"
ENDCOLOR="\033[0m"

ifndef V
QUIET_CC = @printf '    %b %b\n' $(CCCOLOR)CC$(ENDCOLOR) $(SRCCOLOR)$@$(ENDCOLOR) 1>&2;
QUIET_AR = @printf '    %b %b\n' $(LINKCOLOR)AR$(ENDCOLOR) $(BINCOLOR)$@$(ENDCOLOR) 1>&2;
QUIET_JAVAC = @printf '    %b %b\n' $(CCCOLOR)JAVAC$(ENDCOLOR) $(SRCCOLOR)$@$(ENDCOLOR) 1>&2;
QUIET_JAVAH = @printf '    %b %b\n' $(CCCOLOR)JAVAH$(ENDCOLOR) $(SRCCOLOR)$@$(ENDCOLOR) 1>&2;
QUIET_LINK = @printf '    %b %b\n' $(LINKCOLOR)LINK$(ENDCOLOR) $(BINCOLOR)$@$(ENDCOLOR) 1>&2;
QUIET_INSTALL = @printf '    %b %b\n' $(LINKCOLOR)INSTALL$(ENDCOLOR) $(BINCOLOR)$@$(ENDCOLOR) 1>&2;
endif
