arena.o: arena.c arena.h indexer.h config.h
bloom_builder.o: bloom_builder.c bloom_builder.h buffer.h lib/kvec.h \
 sst_block_builder.h variant.h hash.h utils.h indexer.h config.h
buffer.o: buffer.c buffer.h indexer.h config.h utils.h variant.h
compaction.o: compaction.c compaction.h variant.h buffer.h vector.h sst.h \
 indexer.h config.h skiplist.h arena.h sst_loader.h lib/kvec.h file.h \
 sst_builder.h sst_block_builder.h bloom_builder.h merger.h heap.h \
 utils.h
crc32.o: crc32.c crc32.h indexer.h config.h utils.h variant.h buffer.h
db.o: db.c db.h indexer.h config.h sst.h skiplist.h arena.h variant.h \
 buffer.h sst_loader.h lib/kvec.h file.h sst_builder.h \
 sst_block_builder.h bloom_builder.h vector.h memtable.h merger.h heap.h \
 utils.h
file.o: file.c indexer.h config.h file.h buffer.h
hash.o: hash.c hash.h utils.h variant.h buffer.h
heap.o: heap.c heap.h
indexer.o: indexer.c indexer.h config.h
lru.o: lru.c lru.h
memtable.o: memtable.c memtable.h skiplist.h arena.h config.h variant.h \
 buffer.h utils.h indexer.h
merger.o: merger.c compaction.h variant.h buffer.h vector.h sst.h \
 indexer.h config.h skiplist.h arena.h sst_loader.h lib/kvec.h file.h \
 sst_builder.h sst_block_builder.h bloom_builder.h merger.h heap.h \
 utils.h
skiplist.o: skiplist.c skiplist.h arena.h config.h variant.h buffer.h \
 utils.h indexer.h
sst.o: sst.c sst.h indexer.h config.h skiplist.h arena.h variant.h \
 buffer.h sst_loader.h lib/kvec.h file.h sst_builder.h \
 sst_block_builder.h bloom_builder.h vector.h memtable.h utils.h heap.h \
 compaction.h merger.h
sst_block_builder.o: sst_block_builder.c sst_block_builder.h lib/kvec.h \
 buffer.h variant.h indexer.h config.h
sst_builder.o: sst_builder.c sst_builder.h indexer.h config.h file.h \
 buffer.h sst_block_builder.h lib/kvec.h variant.h bloom_builder.h \
 crc32.h
sst_loader.o: sst_loader.c sst_loader.h lib/kvec.h file.h indexer.h \
 config.h buffer.h variant.h utils.h crc32.h hash.h
utils.o: utils.c utils.h variant.h buffer.h indexer.h config.h
vector.o: vector.c vector.h
